### ISSUE TITLE
Fronius AKU

### ISSUE THREAD

**Issue by chatis** [ayasystems/froniusHttp#4]
Hello,

I haven't an AKU, but I'm really interested about having data from the grid or from my solar panel in live... Because from type Fronius instead of Fronius AKU

 we haven't those data...

But even I choose it, my data stay to 0. Any idea why ?
<img width="1113" alt="Capture d’écran 2020-12-15 à 10 00 05" src="https://user-images.githubusercontent.com/4694026/102193397-54a7f800-3ebc-11eb-9f47-8f0ec4e247dd.png">
<img width="716" alt="Capture d’écran 2020-12-15 à 09 57 04" src="https://user-images.githubusercontent.com/4694026/102193410-583b7f00-3ebc-11eb-8f2a-672e2ba584f6.png">
<img width="668" alt="Capture d’écran 2020-12-15 à 09 56 32" src="https://user-images.githubusercontent.com/4694026/102193414-58d41580-3ebc-11eb-8f7c-3e4a83386176.png">

**Comment by ajarzyn** [comment]
I do not understand what is the problem.
If you do not have battery then change `Inverter model`

And remove all the devices that are not related to your inverter.
